services:
  userservice:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - eshop-network

  productservice:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - eshop-network

  cartservice:
    build:
      context: .
      dockerfile: CartService/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - eshop-network

  invoiceservice:
    build:
      context: .
      dockerfile: InvoiceService/Dockerfile
    ports:
      - "5004:80"
    depends_on:
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - eshop-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - eshop-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - eshop-network

networks:
  eshop-network:
    driver: bridge
